[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.install]
cmds = [
  "npm install --include=dev",
  "cd client && npm install --include=dev"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "./start.sh"